package Interfaces;

import java.util.HashMap;
import java.util.Map;
import Elements.DijikstraModel;
import Elements.Sommet;
import java.awt.Color;
import java.awt.Font;

public class ResultatCourtChemin extends javax.swing.JDialog {
    private Sommet depart;
    private HashMap<String,Double> l;
    private HashMap<String,String> p;

    public ResultatCourtChemin(java.awt.Frame parent,Sommet depart, HashMap<String,Double> l, HashMap<String,String> p) {
        super(parent, true);
        getContentPane().setBackground(new Color(255, 235, 205));
        this.depart = depart;
        this.l = l;
        this.p = p;
        initComponents();
        label_depart.setText(depart.toString());
        table_resultat.setModel(new DijikstraModel(this.l, this.p));
        
        StringBuffer sb = new StringBuffer();
        
        for (Map.Entry<String, Double> entry : l.entrySet()) {
            String key = entry.getKey(); Double value = entry.getValue();
            
            if(!key.equals(depart.getLabel())){
                
                StringBuffer line = new StringBuffer();
                line.append(":"+value+"");//cout
                line.insert(0, "->"+key);
                String pre = p.get(key);
                while((pre!=null) && !pre.equals(depart.getLabel())){
                    line.insert(0, "->"+pre);
                    pre = p.get(pre);
                }
                line.insert(0, pre);
                if(pre!=null)sb.append(line.toString()+"\n");
            }
        }
        console_resultat.setText(sb.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_resultat = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        console_resultat = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setFont(new Font("Tahoma", Font.BOLD, 11));
        jLabel1.setForeground(new Color(178, 34, 34));
        label_depart = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setFont(new Font("Tahoma", Font.BOLD, 11));
        jLabel2.setForeground(new Color(178, 34, 34));
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        table_resultat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane1.setViewportView(table_resultat);

        console_resultat.setColumns(20);
        console_resultat.setRows(5);
        jScrollPane2.setViewportView(console_resultat);

        jLabel1.setText("Sommet de depart: ");

        jLabel2.setText("Les chemins/couts:");

        jLabel3.setText("p");

        jLabel4.setText("l");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_depart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(label_depart))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, label_depart});

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private javax.swing.JTextArea console_resultat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_depart;
    private javax.swing.JTable table_resultat;
}
